In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/home/igodzwon/Project_AI/data/concept_refinement_mapped.csv")
df

,id,original,note,mapped_concept
0,0,Language - Telugu,"Telugu, found in Telangana and Andhra Pradesh,...",script_south_indian
1,1,Unique Railroad,A railroad can be seen along almost the entire...,railroad
2,2,Sugarcane Plantations,\nSugarcane plantations are most commonly seen...,vegetation_crops
3,3,Hip roofs,Western “hip” roofs predominate in the South a...,building_roof
4,4,Poles,Cambodia for the most part uses two types of p...,pole_shape
...,...,...,...,...
7284,7284,Car Meta - Boxy Car - Odisha,A boxy car with an extra step at the front is ...,car_meta
7285,7285,Solok Selatan (South) Regency,\nCapital City: Padang Aro\nType: Regency\nPop...,landscape_tropical
7286,7286,Infrastructure - Assam / West Bengal vans,"These vans (can be white, red, or orange) with...",car_type
7287,7287,Salatiga Kota,\nCapital City:\nType: Kota\nPopulation: 19232...,landscape_urban
7288,7288,Luwu Utara (North) Regency,\nCapital City: Masamba\nType: Regency\nPopula...,landscape_tropical

In [13]:
df_original = pd.read_csv("/home/igodzwon/Project_AI/data/6921d7831744c5356b098bf7_balanced/dataset.csv")

#clean df note from html tags
df_original['note'] = df_original['note'].str.replace('<[^<>]*>', '', regex=True)

#clean df note from html tags
df_original['note'] = df_original['note'].str.replace('<[^<>]*>', '', regex=True)

In [14]:
(df_original
 .groupby(['meta_name', 'note'])
 .size()
 .reset_index(name='count')
 .sort_values('count', ascending=False))

,meta_name,note,count
118,95,\ngen 3 (Australia gen 3 always has long anten...,219
5119,RN14,"Where : eastern Entre Rios, southern Corriente...",217
5191,RP55 & RN148,"Where : eastern San Luis, from Arizona to Vill...",173
1383,Chiloé Island,Chiloé island is very recognizable due to its ...,146
5610,Ruta 9,Ruta 9 in Magallanes is a unique concrete road...,129
...,...,...,...
2488,Infrastructure - Alaskan Pipeline,The Alaskan pipeline which is usually visible ...,1
2487,Infrastructure - Alagoas Lamp,Different colors possible,1
2486,Infrastructure - Aksa,Aksa Doğalgaz is found in many different provi...,1
2485,Infrastructure - Akmercan,Akmercan is another trans-provincial company t...,1
6104,Succulents,This stretch of the B8 just north of Kibaoni h...,1